import numpy as np
list_ = [ ‘1’ , ’2’ , ‘3’ , ‘4’ , ‘5’ ]
array_list = np.array(object = list_)

Q1. Is there any difference in the data type of variables list_ and array_list? If there is then write a code
to print the data types of both the variables.

yes, there is difference in data tyes of variable list_ is list and array_list is array 

In [1]:
import numpy as np

In [2]:
list_ = [ '1' , '2', '3' , '4' , '5' ]

In [9]:
array_list = np.array(object = list_)

In [10]:
array_list

array(['1', '2', '3', '4', '5'], dtype='<U1')

In [4]:
type(list_)

list

In [5]:
type(array_list)

numpy.ndarray

Q2. Write a code to print the data type of each and every element of both the variables list_ and
arra_list.

Consider the below code to answer further questions:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [1]:
import numpy as np
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]
num_array = np.array(object = num_list)

In [2]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [3]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [5]:
type(num_array)

numpy.ndarray

In [4]:
type(num_list)

list

Q3. Considering the following changes in the variable, array_list:

In [11]:
array_list = np.array(object = list_, dtype = int)

In [12]:
array_list

array([1, 2, 3, 4, 5])

Q4. Write a code to find the following characteristics of variable, num_array:
(i) shape
(ii) size

In [36]:
num_list = [ [ 1 , 2 , 3 ] , [ 4 , 5 , 6 ] ]

In [37]:
num_list

[[1, 2, 3], [4, 5, 6]]

In [34]:
num_array = np.array(object = num_list)

In [38]:
num_array

array([[1, 2, 3],
       [4, 5, 6]])

In [39]:
num_array.size

6

In [40]:
num_array.shape

(2, 3)

Q5. Write a code to create numpy array of 3*3 matrix containing zeros only, using a numpy array
creation function.
[Hint: The size of the array will be 9 and the shape will be (3,3).]

In [25]:
import numpy.matlib as nm

In [28]:
n1=nm.zeros((3,3))

In [29]:
n1

matrix([[0., 0., 0.],
        [0., 0., 0.],
        [0., 0., 0.]])

In [30]:
n1.size

9

In [31]:
n1.shape

(3, 3)

In [13]:
ar2 = np.array([[0,0,0],[0,0,0],[0,0,0]])

In [14]:
ar2

array([[0, 0, 0],
       [0, 0, 0],
       [0, 0, 0]])

Q6. Create an identity matrix of shape (5,5) using numpy functions? [Hint: An identity matrix is a matrix containing 1 diagonally and other elements will be 0.]

In [22]:
import numpy.matlib as nm

In [23]:
nm.eye(5)

matrix([[1., 0., 0., 0., 0.],
        [0., 1., 0., 0., 0.],
        [0., 0., 1., 0., 0.],
        [0., 0., 0., 1., 0.],
        [0., 0., 0., 0., 1.]])